# Generated by Django 4.1 on 2022-08-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total')),
                ('obs', models.CharField(max_length=255, verbose_name='Observação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedido',
            },
        ),
    ]
