# Generated by Django 4.1 on 2022-08-08 17:56

import address.models
from django.db import migrations
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('delivery', '0004_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cod',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=6),
        ),
        migrations.AddField(
            model_name='pedido',
            name='end_entrega',
            field=address.models.AddressField(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
