# Generated by Django 4.1 on 2022-08-11 17:54

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('delivery', '0006_alter_itempedido_pedido_alter_pedido_end_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='endereco',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='address.address'),
        ),
    ]
