# Generated by Django 4.1 on 2022-08-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_restaurante_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='delivery.restaurante', verbose_name='Restaurante'),
        ),
    ]
