GET http://127.0.0.1:8000/api/restaurantes/ HTTP/1.1
content-type: application/json
# Authorization: Basic mauricio:123456

###

GET  http://127.0.0.1:8000/api/restaurantes/5 HTTP/1.1
content-type: application/json
# Authorization: Basic mauricio:123456

# {
#   "nome": "Padaria Ideal",
#   "fone": "88655989",
#   "endereco": 4
# }
###

POST http://127.0.0.1:8000/api/restaurantes/ HTTP/1.1
content-type: application/json
Authorization: Basic mauricio:123456

{
  "nome": "Nordestina",
  "fone": "78857357",
  "endereco": 2
}
###

GET http://127.0.0.1:8000/api/produtos/6 HTTP/1.1
content-type: application/json
# Authorization: Basic mauricio:123456

###

GET http://127.0.0.1:8000/api/pedidos/ HTTP/1.1
content-type: application/json
# Authorization: Basic mauricio:123456

###

GET http://127.0.0.1:8000/api/pedidos/ HTTP/1.1
content-type: application/json
# Authorization: Basic mauricio:123456

###

POST http://127.0.0.1:8080/api/pedidos/add/1/7/ HTTP/1.1
content-type: application/json
Authorization: Basic mauricio:123456

###