GET http://127.0.0.1:8000/api/restaurantes/ HTTP/1.1
content-type: application/json
# Authorization: Basic mauricio:123456

###

GET  http://127.0.0.1:8000/api/restaurantes/5 HTTP/1.1
content-type: application/json
# Authorization: Basic mauricio:123456

# {
#   "nome": "Padaria Ideal",
#   "fone": "88655989",
#   "endereco": 4
# }
###

POST http://127.0.0.1:8000/api/restaurantes/ HTTP/1.1
content-type: application/json
# Authorization: Basic mauricio:123456

{
  "nome": "Delicia Italiana",
  "fone": "867232654",
  "endereco": 2
}
###